Added HeartRate endpoint
SW8-2024/chill-chaser-backend pull request #18
Opened 2024-04-12 11:57 UTC by andreasalstrup

2024-04-15 10:06 UTC, JE-FH requested changes

2024-04-15 10:06 UTC, JE-FH commented on ChillChaser/Migrations/20240412104359_AddHeartrate.cs
Jeg er med på det her er auto genereret men det er lidt sus den ikke engang laver en ny tabel 😅. Prøv at pull det nyeste fra main, når PR #15 er kommet ind,

2024-04-15 10:06 UTC, JE-FH commented on ChillChaser/Services/impl/HeartRateService.cs
> +            ctx.HeartRates.Add(new Models.DB.HeartRate
Fedt nok, men kan vi få en `AddAsync` istedet? :D

2024-04-16 07:52 UTC, andreasalstrup commented on ChillChaser/Services/impl/HeartRateService.cs
> +            ctx.HeartRates.Add(new Models.DB.HeartRate
Fixed

2024-04-16 08:02 UTC, andreasalstrup commented on ChillChaser/Migrations/20240412104359_AddHeartrate.cs
Pull fra main giver samme resultat med `dotnet ef migrations add AddHeartrate` :thinking:

2024-04-16 09:11 UTC, JE-FH approved these changes
LGTM

2024-04-16 09:11 UTC, merged